{{- $namespace := .Values.namespace -}}
{{- $env := .Values.env -}}
{{- $secretName := .Values.storage.secretName -}}

kind: Secret
apiVersion: v1
metadata:
  name: "bereshit-sr-{{ $env }}-secret"
  namespace: {{ $namespace }}
data:
  password: {{ default "" .Values.dbs.bereshit_sr_ssd.password | b64enc | quote }}
  username: {{ default "" .Values.dbs.bereshit_sr_ssd.username | b64enc | quote }}
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: "sr-3d-layers-{{ $env }}-secret"
  namespace: {{ $namespace }}
data:
  password: {{ default "" .Values.dbs.sr_3d_layers.password | b64enc | quote }}
  username: {{ default "" .Values.dbs.sr_3d_layers.username | b64enc | quote }}
type: Opaque